/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type AlertKind =
  | "TokenApprovalWalletDrainer"
  | "GaslessTransaction"
  | "Honeypot"
  | "PriceMedium"
  | "CollectionBidAboveFloor";
export type Severity = "High" | "Medium" | "Low";
export interface Revert {
  message?: string | null;
}
export type Simulation =
  | {
    revert: Revert;
  }
  | {
    success: any;
  };

export interface ProcessedSimulation {
  simulation: Simulation;
  alerts: Alert[];
}
export interface Alert {
  /**
   * Alert we detected.
   */
  kind: AlertKind;
  /**
   * Human readable message.
   */
  msg: string;
  severity: Severity;
}
